# Generated by Django 4.2 on 2024-10-30 10:03

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cta_img',
            field=models.ImageField(default='default.jpg', upload_to=services.models.Service.get_path),
        ),
    ]
