# Generated by Django 4.2 on 2024-11-01 14:10

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_accreditation_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='accreditation_img',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.Service.get_path),
        ),
    ]
