# Generated by Django 4.2 on 2024-11-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_homepage_description_service_homepage_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(default='This is the default meta description', max_length=155),
        ),
    ]
