# Generated by Django 4.2 on 2024-10-27 10:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('thumbnail', models.ImageField(upload_to=blog.models.Article.get_path)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('body_img', models.ImageField(upload_to=blog.models.Article.get_path)),
            ],
        ),
    ]
