# Generated by Django 4.2 on 2024-10-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='intro',
            field=models.TextField(default='This is the intro'),
        ),
        migrations.AddField(
            model_name='article',
            name='lead_paragraph',
            field=models.TextField(default='This is the lead paragraph'),
        ),
    ]
