# Generated by Django 4.2 on 2024-10-28 15:29

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=home.models.Review.get_path)),
                ('name', models.CharField(max_length=30)),
                ('association', models.CharField(max_length=30)),
                ('review', models.TextField()),
                ('snippet', models.TextField()),
            ],
        ),
    ]
