# Generated by Django 4.2 on 2024-11-05 14:41

import colorfield.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosaic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=home.models.Mosaic.get_path)),
                ('backgroundColor', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('bigNum', models.CharField(max_length=5)),
                ('symbol', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=120)),
            ],
        ),
    ]
