# Generated by Django 4.2 on 2024-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mosaic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaic',
            name='link_text',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
    ]
