# Generated by Django 4.2 on 2024-11-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mosaic_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='link_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
