# Generated by Django 4.2 on 2024-11-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_mosaic_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='bigNum',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='symbol',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
