# Generated by Django 4.2 on 2024-11-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_mosaic_bignum_alter_mosaic_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='title',
            field=models.CharField(default='Title Text', max_length=120),
        ),
    ]
