# Generated by Django 4.2 on 2024-11-05 14:52

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_mosaic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=home.models.Mosaic.get_path),
        ),
    ]
