# Generated by Django 4.2 on 2024-11-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_mosaic_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
