# Generated by Django 4.2 on 2024-11-05 18:33

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_mosaic_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.TextField()),
                ('intro', models.TextField()),
                ('img', models.ImageField(upload_to=home.models.IntroGrid.get_path)),
                ('cta_img', models.ImageField(upload_to=home.models.IntroGrid.get_path)),
            ],
        ),
    ]
