# Generated by Django 4.2 on 2024-11-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_introgrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='introgrid',
            name='title',
            field=models.CharField(default='Title Text', max_length=120),
        ),
    ]
