# Generated by Django 4.2 on 2024-10-28 09:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(default='This is the description')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('thumbnail', models.ImageField(upload_to=portfolio.models.Portfolio.get_path)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('img_one', models.ImageField(upload_to=portfolio.models.Portfolio.get_path)),
                ('img_two', models.ImageField(upload_to=portfolio.models.Portfolio.get_path)),
                ('img_three', models.ImageField(upload_to=portfolio.models.Portfolio.get_path)),
                ('img_four', models.ImageField(upload_to=portfolio.models.Portfolio.get_path)),
                ('img_five', models.ImageField(upload_to=portfolio.models.Portfolio.get_path)),
                ('img_six', models.ImageField(upload_to=portfolio.models.Portfolio.get_path)),
                ('img_seven', models.ImageField(upload_to=portfolio.models.Portfolio.get_path)),
                ('img_eight', models.ImageField(upload_to=portfolio.models.Portfolio.get_path)),
                ('img_nine', models.ImageField(upload_to=portfolio.models.Portfolio.get_path)),
                ('img_ten', models.ImageField(upload_to=portfolio.models.Portfolio.get_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.category')),
            ],
        ),
    ]
