# Generated by Django 4.2 on 2024-10-30 11:51

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img_eight',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.Portfolio.get_path),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img_nine',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.Portfolio.get_path),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img_seven',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.Portfolio.get_path),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img_ten',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.Portfolio.get_path),
        ),
    ]
